name: Set Issue Aquad for Support
on:
  issues:
    types:
      - opened
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      repository-projects: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup GitHub CLI
        uses: cli/cli-action@v2

      - name: Authenticate GitHub CLI
        run: gh auth setup-git
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          # Variables
          ISSUE_URL="${{ github.event.issue.html_url }}"
          ISSUE_NUMBER=${{ github.event.issue.number }}
          ORG="abykoshy"
          PROJECT_NUMBER=1
          FIELD_NAME="Team"
          FIELD_VALUE="fromaction"
          PROJECT_ID=$(gh api graphql -f query='
            query{
              user(login: "'$ORG'"){
                projectV2(number: '$PROJECT_NUMBER') {
                  id
                }
              }
            }' | jq -r '.data.user.projectV2.id')
          PROJECT_FIELD_ID=$(
            gh api graphql -f query='
            query{
            node(id: "'$PROJECT_ID'") {
              ... on ProjectV2 {
                fields(first: 20) {
                  nodes {
                    ... on ProjectV2Field {
                      id
                      name
                    }
                    ... on ProjectV2IterationField {
                      id
                      name
                      configuration {
                        iterations {
                          startDate
                          id
                        }
                      }
                    }
                    ... on ProjectV2SingleSelectField {
                      id
                      name
                      options {
                        id
                        name
                      }
                    }
                  }
                }
              }
            }
            }'  | jq -r '.data.node.fields.nodes[] | select(.name == "Team") | .id')
          PROJECT_ISSUE_NUMBER=$(gh api graphql -f query='
            query {
              node(id: "'$PROJECT_ID'") {
                ... on ProjectV2 {
                  items(first: 100) {
                    nodes {
                      id
                      content {
                        ... on Issue {
                          id
                          number
                          title
                        }
                      }
                    }
                  }
                }
              }
            }'  | jq '.data.node.items.nodes[] | select(.content.number == '$ISSUE_NUMBER') | .id')
          gh api graphql -f query='
            mutation {
              updateProjectV2ItemFieldValue(
                input: {
                  projectId: "'$PROJECT_ID'"
                  itemId: "'$PROJECT_ISSUE_NUMBER'"
                  fieldId: "'$PROJECT_FIELD_ID'"
                  value: {
                    singleSelectOptionId: "fromaction"
                  }
                }
              ) {
                projectV2Item {
                  id
                }
              }
            }'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: triage
