name: Set Issue Aquad for Support
on:
  issues:
    types:
      - opened
jobs:
  label_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Set field
        run: |
          # Variables
          ISSUE_URL="${{ github.event.issue.html_url }}"
          ISSUE_NUMBER=${{ github.event.issue.number }}
          OWNER=abykoshy
          PROJECT_NUMBER=1
          FIELD_NAME=Team
          FIELD_VALUE=fromaction
          PROJECT_ID=$(gh project list --owner $OWNER --format json | jq -r '.projects[] | select(.number == $PROJECT_NUMBER) | .id')
          ISSUE_ITEM_ID=$(gh project item-list --owner $OWNER $PROJECT_NUMBER --format json | jq -r '.items[] | select(.content.number == $ISSUE_NUMBER) | .id')
          FIELD_ID=$(gh project field-list $PROJECT_NUMBER --owner $OWNER --format json | jq -r '.fields[] | select(.name == "Team") | .id')
          FIELD_OPTION_ID=$(gh project field-list $PROJECT_NUMBER --owner $OWNER --format json | jq -r '.fields[] | select(.name == "Team") | .options[] | select(.name == "fromaction") | .id')

          gh project item-edit --project-id $PROJECT_ID --field-id $FIELD_ID --single-select-option-id $FIELD_OPTION_ID --id $FIELD_ID
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: triage
